name: Deploy khulnasoft.github.io
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */4 * * *" 

jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        sudo apt-get install jupyter unzip -y --fix-missing
        python -m pip install nbconvert
        python -m pip install --upgrade pip -r requirements.txt
        
    - name: Grab Needed Data
      run: |
        wget -q  https://nvd.handsonhacking.org/nvd.jsonl
        wget -q https://raw.githubusercontent.com/CVEProject/cve-website/main/src/assets/data/CNAsList.json
        ls -lh 
    - name: Run Notebooks
      env:
        GH_TOKEN:  ${{ secrets.ORG_REPO_TOKEN }}
      run: |
         jupyter nbconvert  --to notebook --inplace --execute CVEAll.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2016.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2017.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2018.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2019.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2020.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2021.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2022.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2023.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVE2024.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVECNAMap.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVECalendar.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVEGrowth.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVECVSS.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVECNA.ipynb
         jupyter nbconvert  --to notebook --inplace --execute CVECWE.ipynb
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          default_author: github_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the book
      run: |
        jupyter-book build .

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        cname: khulnasoft.github.io
